### PR TITLE
idempotent Parse - req body is no longer 'consumed' with Parse

### PR DESCRIPTION
**Pull request by mslusarczyk**
Parse should not affect `req` that is passed to it.

### CODE REVIEW

**Comment by rjz** [comment]
Thanks, @mslusarczyk, this seems like a reasonable behavior!

Before merging, could you help me understand the case that motivated the change? Particularly interested in whether it makes sense to re-allocate the `body` in all cases, or whether we should make it an opt-in decision via a separate method.

**Comment by mslusarczyk** [comment]
Sure. I'm building validation-proxy, I want to check if `req` is valid webhook and pass it along. 
With current master version I get `net/http: http: ContentLength=222 with Body length 0` because Parse is reading req.Body. Creating separate method sounds good, if you prefer not to include it at all let me know. I can handle it on my side.

**Comment by rjz** [comment]
Got it, and makes total sense. I think it might be best to leave the body copy/replacement up to the proxy (cloning the inbound request actually seems like a generally useful defense for a proxy), but I'd love to revisit this if others report similar issues.

Thanks again, @mslusarczyk, and please don't hesitate to file any other issues you run into (or a link back to the finished proxy :^))!

**Comment by mslusarczyk** [comment]
Cool, closing this PR for now.

**Pull request closed without merging**
